import numpy as np

######################################################################

def generate_pseudos(n=1, seed=0):
    np.random.seed(seed)
    right_ = np.random.choice(right*int(np.ceil(n/len(right))),
        size=n, replace=False)
    left_ = np.random.choice(left*int(np.ceil(n/len(left))),
        size=n, replace=False)
    pseudos = [x + " " + y for x, y in zip(left_, right_)]
    return pseudos

right = [
    "Agnarr",
    "Anna",
    "Bulda",
    "Elsa",
    "Hans",
    "Iduna",
    "Kristoff",
    "Oaken",
    "Olaf",
    "Pabbie",
    "Runeard",
    "Sitron",
    "Sven",
    "Yelana",
    ]

left = [
    "admiring",
    "adoring",
    "agitated",
    "amazing",
    "angry",
    "awesome",
    "berserk",
    "big",
    "boring",
    "clever",
    "cocky",
    "cranky",
    "desperate",
    "determined",
    "distracted",
    "dreamy",
    "drunk",
    "ecstatic",
    "elated",
    "elegant",
    "evil",
    "fervent",
    "focused",
    "furious",
    "gigantic",
    "gloomy",
    "goofy",
    "grave",
    "happy",
    "high",
    "hopeful",
    "hungry",
    "insane",
    "jolly",
    "jovial",
    "kickass",
    "lonely",
    "loving",
    "mad",
    "modest",
    "naughty",
    "nauseous",
    "nostalgic",
    "pedantic",
    "pensive",
    "prickly",
    "reverent",
    "romantic",
    "sad",
    "serene",
    "sharp",
    "sick",
    "silly",
    "sleepy",
    "small",
    "stoic",
    "stupefied",
    "suspicious",
    "tender",
    "thirsty",
    "tiny",
    "trusting",
    ]